### ISSUE TITLE
Don't commit Build Files

### ISSUE THREAD

**Issue by VincentWo** [karlbeecken/atem-neopixel-tally#1]
main.js is a build file and shouldn't be committed and I think it is deeply wrong that you did that.

**Comment by karlbeecken** [comment]
Hey! You are deeply welcome to just add the file to the .gitignore and create a tsconfig with incremental builds at the same time.
Thanks for your time and interest in this project!

**Comment by VincentWo** [comment]
I am sorry. I am a very busy man and don't have time in my schedule for pesky things like editing .gitignore files and doing config.
I have, however, a good friend of mine, who is quite versed in DevOps, maybe he can help you setting this up.

And I don't want to be the want to complain, but I tried to help this project by offering constructive criticism and you responsded with nothing but hate. I don't think this "Holier than thou"-Attitude will take you very far to be honest. Not wanting to be mean, just honest.

**Comment by chronikum** [comment]
Hello Mr karlbeecken, I am just here to inform you that mr vincentwo is very, very right.
I can help you setting this up!
I have experiences in over 20+ years in typescript.

**Comment by karlbeecken** [comment]
Hello Mr chronikum. I have informations by the NSA that you are under 25 years, so you DON'T HAVE 20+ YEARS EXPERIENCE IN TYPESCRIPT!

(or you have a certain delorion, who knows)
